# Trench Crusade - Supply Depots
# depots.inc

province = {
  id = 61 # London
  supplypool = 20
}
province = {
  id = 62 # Southeast England
  supplypool = 5
}
province = {
  id = 68 # Northern England
  supplypool = 5
}
province = {
  id = 64 # Berlin
  supplypool = 15
}
province = {
  id = 81 # Rhineland
  supplypool = 8
}
province = {
  id = 82 # Westphalia
  supplypool = 6
}
province = {
  id = 799 # New Antioch
  supplypool = 10
  oilpool = 2
}
province = {
  id = 800 # Latakia
  supplypool = 5
}
province = {
  id = 802 # Tripoli
  supplypool = 5
}
province = {
  id = 783 # Konya
  supplypool = 12
  oilpool = 5
}
province = {
  id = 784 # Ankara
  supplypool = 6
  oilpool = 2
}
province = {
  id = 700 # Aleppo
  supplypool = 6
  oilpool = 3
}
province = {
  id = 801 # Acre
  supplypool = 5
}
province = {
  id = 118 # Rome
  supplypool = 8
}
province = {
  id = 88 # Warsaw
  supplypool = 8
}
province = {
  id = 153 # Budapest
  supplypool = 8
}
province = {
  id = 295 # Novgorod
  supplypool = 8
}
province = {
  id = 284 # Kyiv
  supplypool = 6
}
province = {
  id = 66 # Oslo
  supplypool = 5
}
province = {
  id = 620 # Addis Ababa
  supplypool = 6
}
province = {
  id = 461 # Marrakesh
  supplypool = 4
}
province = {
  id = 460 # Carthage
  supplypool = 4
}
province = {
  id = 550 # Timbuktu
  supplypool = 4
}
province = {
  id = 85 # Hamburg (GER)
  supplypool = 15
}
province = {
  id = 790 # Mammon's Forge
  supplypool = 20
}
province = {
  id = 810 # Samael's Throne
  supplypool = 15
  oilpool = 5
}
province = {
  id = 820 # Iblis Citadel
  supplypool = 10
  oilpool = 10
}
province = {
  id = 388 # Nicosia (YUG)
  supplypool = 10
  oilpool = 3
}
province = {
  id = 160 # Targoviste (BUL)
  supplypool = 8
}
province = {
  id = 795 # Beelzebub's Seat
  supplypool = 8
}
province = {
  id = 815 # Lilith's Domain
  supplypool = 6
  oilpool = 2
}
province = {
  id = 465 # Sarai (MON)
  supplypool = 4
  oilpool = 1
}
province = {
  id = 500 # Tobolsk (TIB)
  supplypool = 4
  oilpool = 1
}
