###############################
# Victory points distribution #
# Trench Crusade 1905         #
###############################

province = { id = 799    points = 5 } # New Antioch
province = { id = 61     points = 5 } # London
province = { id = 64     points = 5 } # Berlin (PRU)
province = { id = 783    points = 4 } # Konya (TUR capital)
province = { id = 801    points = 3 } # Acre (HOL)
province = { id = 118    points = 3 } # Rome (POR)
province = { id = 88     points = 3 } # Warsaw (POL)
province = { id = 153    points = 3 } # Budapest (HUN)
province = { id = 295    points = 3 } # Novgorod (RUS)
province = { id = 284    points = 3 } # Kyiv (UKR)
province = { id = 66     points = 2 } # Oslo (NOR)
province = { id = 110    points = 2 } # Dublin (HON)
province = { id = 112    points = 2 } # Edinburgh (ALB)
province = { id = 620    points = 3 } # Addis Ababa (ETH)
province = { id = 550    points = 2 } # Timbuktu (NZL)
province = { id = 461    points = 2 } # Marrakesh (LUX)
province = { id = 460    points = 2 } # Carthage (LIB)
province = { id = 85     points = 5 } # Hamburg (GER)
province = { id = 160    points = 4 } # Targoviste (BUL)
province = { id = 790    points = 5 } # Mammon's Forge
province = { id = 810    points = 5 } # Samael's Throne
province = { id = 820    points = 4 } # Iblis Citadel
province = { id = 388    points = 4 } # Nicosia (YUG)
province = { id = 798    points = 4 } # Pilgrim Fortress
province = { id = 800    points = 4 } # Latakia Coast
province = { id = 802    points = 3 } # Tripoli Coast
province = { id = 807    points = 3 } # Jordan Valley
province = { id = 815    points = 3 } # Lilith's Domain
province = { id = 465    points = 2 } # Sarai (MON)
province = { id = 500    points = 2 } # Tobolsk (TIB)
